### ISSUE TITLE
Swallowing errors

### ISSUE THREAD

**Issue by confuser** [apigee-127/magic#16] opened 2016-01-22 12:11 UTC
Please see https://github.com/apigee-127/swagger-tools/issues/327 for more information

The `.init` function is not following standard `callback(error, result)` style which makes it impossible to pass back any errors.

**Comment by whitlockjc** [comment] 2016-01-22 16:20
swagger-tools' `initializeMiddleware` was not ever intended to be an _"error-first callback"_ and is not documented to be.  There is no safe way to handle an error so passing it back to the caller makes no sense.  The code in swagger-tools is doing the right thing.  This issue is caused by the version of json-refs in swagger-tools being broken so upgrading to a version that fixes it should fix this issue.

I've now had to reply with a similar response to three separate projects so can we somehow just do this in one place?  Fixing this in swagger-tools@0.9.x means magic will get the fix automatically and itself does not require any changes to fix this.  I will let @theganyo decide whether or not to close this as it's already being addressed in swagger-tools.

**Comment by confuser** [comment] 2016-01-22 16:25
Then can someone explain how I'm supposed to figure out why my Node.js application is crashing when these modules simply hide the error message which would immediately give me an answer on your platform?

To reproduce from the very README on this project:

```js
var a127 = require('a127-magic');
var app = require('express')();

a127.init(function(config) {
  throw new Error('You should see this, but you do not');
  app.use(a127.middleware(config));
  app.listen(process.env.PORT || 10010);
});
```

Process exits, no error, nothing. How is this a feature?

**Comment by whitlockjc** [comment] 2016-01-22 16:31
I think I've figured it out.  I'm closing this and we'll discuss at swagger-tools as this is a swagger-tools issue.

**Closed by whitlockjc** 2016-01-22 16:31 UTC
